services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db
    ports:
      - 5432:5432

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - 8081:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=triptap@google.com
      - PGADMIN_DEFAULT_PASSWORD=triptap123

  backend:
    build: .
    container_name: triptap_backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/db
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001
    ports:
      - "8080:3000" # expone el backend en localhost:8080
    volumes:
      - ./triptap-backend:/app
    command: pnpm start:dev
