services:
  - type: web
    runtime: node
    name: triptap-backend
    plan: free
    buildCommand: pnpm install && pnpm prisma generate && pnpm build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://trip-trap.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: triptap-db
          property: connectionString

databases:
  - name: triptap-db
    plan: free
    databaseName: triptap
    user: triptap_user
